#!/usr/bin/bash
# See https://man.sr.ht/~kennylevinsen/greetd/

# Set environment variables
export XDG_SESSION_TYPE=wayland
export XDG_SESSION_DESKTOP=sway
export XDG_CURRENT_DESKTOP=sway
export DESKTOP_SESSION=sway
export MOZ_ENABLE_WAYLAND=1

for file in /etc/profile ~/.profile; do
    if [ -f "$file" ]; then
        source "$file"
    fi
done

if [ -x /usr/bin/sway-git ]; then
    sway_cmd="sway-git"
else
    sway_cmd="sway"
fi

# Show sway logs under journalctl
systemd-cat --identifier sway "$sway_cmd" "$@"
