[target.sway]
install = [
    "bin/start-polkit-agent",
    "bin/lock-wrapper",
    "bin/kbbacklight_toggle",
    "bin/backlight",
    "https://github.com/bR3iN/sway-scratchpad-waybar/releases/download/v0.1.0/sway-scratchpad-waybar-0.1.0-x86_64-linux-gnu",
]

system_install = [
    "Sway/session",
]

cmds = [
    "cp -n ~/.config/sway/config-template ~/.config/sway/config.d/config.local",
    "cp -n ~/.config/kanshi/config-template ~/.config/kanshi/config",
]

[target.sway.links]
".config/sway" = "Sway/sway"
".config/waybar" = "Sway/waybar"
".config/kanshi" = "Sway/kanshi"
".config/mako" = "Sway/mako"

[target.tmux.links]
".config/tmux" = "tmux"


[target.neovim]
links = {".config/nvim" = "nvim"}


[target.fonts]
cmds = ["hooks/setup/fonts.sh"]

[target.wallpaper]
cmds = [
    "hooks/setup/wallpaper.sh",
]


[target.kitty]
links = {".config/kitty" = "kitty"}

[target.wofi]
links = {".config/wofi" = "wofi"}
cmds = ["hooks/setup/wofi-emoji.sh"]

[target.rofi-scripts]
links = {".local/libexec/prompt.sh" = "bin/prompt.sh"}
install = [
    "bin/rofi-open",
    "bin/rofi-vpn",
    "bin/rofi-ff",
    "bin/rofi-scripts",
    "bin/rofi-inputs",
    "bin/rofi-askpass",
    "bin/rofi-bookmarks",
]

[target.bash.links]
".bashrc" = "bash/bashrc"
".bash_profile" = "bash/bash_profile"

[target.fish]
links = {".config/fish" = "fish"}
cmds = [
    "sudo mkdir -p /root/.config",
    "sudo cp -r fish /root/.config",
]

[target.bat.links]
".config/bat/config" = "bat.conf"

[target.profile]
links = {".profile" = "profile"}
cmds = ["mkdir -p ~/.profile.d"]

[target.qutebrowser.links]
"~/.config/qutebrowser/config.py" = "qutebrowser/qutebrowser.py"
"~/.config/qutebrowser/base16.py" = "qutebrowser/base16.py"

[target.greetd]
system_install = ["greetd"]

[target.git.links]
".config/git/config" = "gitconfig"

[target.emacs.links]
".config/emacs" = "emacs"
