[[item]]
template = "custom"
subtemplate = "wallpaper"
file = "/tmp/current_scheme"
rewrite = true
hook = "~/Wallpaper/set"

[[item]]
template = "zathura"
subtemplate = "recolor"
file = "~/.config/zathura/flavours"
rewrite = true

[[item]]
template = "kitty"
subtemplate = "default-256"
file = "~/.config/kitty/flavours.conf"
rewrite = true

[[item]]
template = "qutebrowser"
file = "~/.config/qutebrowser/flavours.py"
rewrite = true

[[item]]
template = "fzf"
subtemplate = "fish"
file = "~/.config/fish/conf.d/flavours_fzf.fish"
rewrite = true

[[item]]
template = "waybar"
file = "~/.config/waybar/flavours.css"
hook = "killall -USR2 waybar"
rewrite = true

[[item]]
template = "sway"
subtemplate = "colors"
file = "~/.config/sway/flavours"
rewrite = true
hook = "swaymsg reload"
light = false

[[item]]
template = "custom"
subtemplate = "i3"
file = "~/.config/i3/config"
hook = "i3-msg reload"
light = false

# [[item]]
# template = "wofi"
# file = "~/.config/wofi/flavours.css"
# rewrite = true

[[item]]
template = "custom"
subtemplate = "rofi"
file = "~/.config/rofi/flavours.rasi"
rewrite = true

# [[item]]
# template = "custom"
# subtemplate = "wob"
# file = "~/.config/wob"
# rewrite = true

[[item]]
template = "custom"
subtemplate = "mako"
file = "~/.config/mako/config"
rewrite = true

[[item]]
template = "custom"
subtemplate = "polybar"
file = "~/.config/polybar/flavours"
rewrite = true

[[item]]
template = "custom"
subtemplate = "dunst"
file = "~/.config/dunst/dunstrc"
rewrite = true

[[item]]
template = "custom"
subtemplate = "scss"
file = "~/.themes/FlatWaita-16/base16.scss"
rewrite = true
hook = "cd ~/.themes/FlatWaita-16 && make install &"


# vim: nowrap
