#!/usr/bin/bash
LOG=~/.local/share/xorg/i3.log

# set environment
export XDG_SESSION_TYPE=x11
export XDG_SESSION_DESKTOP=i3
export XDG_CURRENT_DESKTOP=i3
export DESKTOP_SESSION=i3

source ~/.bash_profile

# start picom
picom -b

# Create i3 config from sway config
CONFIG=$(mktemp)
~/.local/share/scripts/i3-config-from-sway.sh "$CONFIG"
export I3CONFIG="$CONFIG"

# Start i3
echo "Starting at $(date)" >> $LOG
exec /usr/bin/i3 --config $CONFIG >> $LOG
