#!/usr/bin/bash

# configure X
xrdb -merge ~/.config/X11/Xresources
setxkbmap $(cat ~/.config/X11/Xkbmap)

for file in /etc/X11/xinit/xinitrc.d/* ; do
        . $file
done

# set environment
export XDG_SESSION_TYPE=x11
export XDG_SESSION_DESKTOP=i3
export XDG_CURRENT_DESKTOP=i3
export DESKTOP_SESSION=i3

source ~/.bash_profile

# Start i3
systemd-cat --identifier i3 /usr/bin/i3
