#!/usr/bin/bash

# configure X
source /etc/X11/xinit/xinitrc-common

# set environment
export XDG_SESSION_TYPE=x11
export XDG_SESSION_DESKTOP=i3
export XDG_CURRENT_DESKTOP=i3
export DESKTOP_SESSION=i3

# Start i3
systemd-cat --identifier i3 /usr/bin/i3
