#!/usr/bin/bash
# Toggles ignoring changes of autogenerated files in current git repository

if [ "$1" = on ]; then
    set() {
        echo "Ignoring $@"
        git update-index --assume-unchanged "$@";
    }
elif [ "$1" = off ]; then
    set() {
        echo "Deignoring $@"
        git update-index --no-assume-unchanged "$@";
    }
else
    echo "USAGE: ignore-base16.sh on|off"
    exit 1
fi

git_root=$(git rev-parse --show-toplevel 2>/dev/null)

if [ "$?" -ne 0 ]; then
    echo "ERROR: not a git repository"
    exit 128
fi

echo "Git root: $git_root"

list_files() {
    sed -n 's/rewrite\s\+=\s\+"\(.*\)"/\1/p' ~/.config/base16-colorizer/targets.toml
}

mapfile -t files < <(list_files)

for file in "${files[@]}"; do
    # Will be empty if file doesn't exist
    canonicalized=$(readlink -f "${file/'~'/"$HOME"}")

    if [[ ! "$canonicalized" =~ ^"$git_root" ]]; then
        echo "$file does not exist or is not in git repository"
        continue
    fi

    set "$canonicalized"
done
