[gradience]
rewrite = "~/.var/app/com.github.GradienceTeam.Gradience/config/presets/user/Base16.json"
 hook = "flatpak run --command=gradience-cli com.github.GradienceTeam.Gradience apply --gtk both -n Base16"
 # hook = "flatpak run --command=gradience-cli com.github.GradienceTeam.Gradience apply --gtk both -n Base16 && ~/.local/libexec/propagate-theme.sh"

[dunst]
rewrite = "~/.config/dunst/dunstrc"

[fzf_fish]
rewrite = "~/.config/fish/conf.d/fzf_base16.fish"

[i3]
rewrite = "~/.config/i3/colors.conf"
hook = "i3-msg reload"
enable_if = "[ \"$XDG_SESSION_DESKTOP\" = i3 ]"

[kitty]
rewrite = "~/.config/kitty/base16.conf"

[ghostty]
rewrite = "~/.config/ghostty/themes/base16"

[wezterm]
rewrite = "~/.config/wezterm/base16_colors.lua"

[mako]
rewrite = "~/.config/mako/config"

[neovim]
template = "lua"
rewrite = "~/.config/nvim/lua/base16-colors.lua"

[polybar]
rewrite = "~/.config/polybar/base16"

[qutebrowser]
rewrite = "~/.config/qutebrowser/base16.py"

[rofi]
rewrite = "~/.config/rofi/base16.rasi"

[wofi]
rewrite = "~/.config/wofi/base16"

[sway]
rewrite = "~/.config/sway/base16"

[swaylock]
rewrite = "~/.config/swaylock/config"

# [Wallpaper]
# template = "null"
# rewrite = "/dev/null"
# enable_if = "which wm"
# hook = "wm try-set $SCHEME_NAME"

[waybar]
template = "css"
rewrite = "~/.config/waybar/base16.css"
hook = "killall -SIGUSR2 waybar"

[zathura]
rewrite = "~/.config/zathura/base16"

[helix]
rewrite = "~/.config/helix/themes/base16.toml"

[eww]
template = "scss"
rewrite = "~/.config/eww/base16.scss"

[vieb]
rewrite = "~/.config/Vieb/colors/base16.css"

[zellij]
rewrite = "~/.config/zellij/themes/base16.kdl"

[zen-browser]
rewrite = "~/.config/zen-themes/base16.css"

[emacs]
rewrite = "~/.config/emacs/lisp/base16-colors.el"
