.PHONY: install

SCHEMES_DIR = ~/.local/share/flavours/base16/schemes

install:
	install -m 0644 -D -t $(SCHEMES_DIR)/pop-os    pop-os.yaml
	install -m 0644 -D -t $(SCHEMES_DIR)/reference reference.yaml
	install -m 0644 -D -t $(SCHEMES_DIR)/fedora34  fedora34.yaml
