#!/usr/bin/bash

# tmp file used to store current brightness when toggling
# as well as fallback when file can't be found
TMP_FILE=/tmp/backlight_toggle_current
TOGGLE_FALLBACK="50%"

# default increase/decrese
DEFAULT_CHANGE="5%"

main ()
{
    case "$1" in
        toggle)
            toggle
            ;;
        increase)
            increase
            ;;
        decrease)
            decrease
            ;;
        *)
            set_brightness "$1" &>/dev/null
            ;;
    esac
}

toggle ()
{
    local current=$(get_brightness)
    if [ "$current" != "0" ]; then
        echo "$current" > "$TMP_FILE"
        set_brightness 0
    else
        local old=$(cat "$TMP_FILE" 2>/dev/null)
        if [ -n "$old" ]; then
            set_brightness "$old"
        else
            set_brightness "$TOGGLE_FALLBACK"
        fi
    fi
}

increase ()
{
    set_brightness +"$DEFAULT_CHANGE"
}

decrease ()
{
    set_brightness "$DEFAULT_CHANGE"-
    if [ "$(get_brightness)" = "0" ]; then
        set_brightness 1
    fi
}

set_brightness ()
{
    # Set brightness and print current brightness as
    # absulute value and as percentage to stdout (e.g 2345 40)
    # brightnessctl set "$1" \
    #     | sed -n 's/.*Current brightness: \([0-9]*\) (\(.*\)%)/\1 \2/p'
    brightnessctl set "$1" > /dev/null
}

get_brightness()
{
    brightnessctl get
}

main "$@"
