#!/usr/bin/bash
set -e
set -u
set -o pipefail

# tmp file used to store current brightness when toggling
# as well as fallback when file can't be found
TMP_FILE=/tmp/backlight_toggled_off
TOGGLE_FALLBACK="50%"

# default increase/decrese
DEFAULT_CHANGE="5%"

main() {
    case "$1" in
        toggle)
            toggle
            ;;
        increase)
            increase
            ;;
        decrease)
            decrease
            ;;
        listen)
            listen
            ;;
        set-clipped)
            set_clipped "$2"
            ;;
        *)
            echo "Invalid subcommand '$1'"
            exit 1
            ;;
    esac
}

toggle() {
    if [ ! -f "$TMP_FILE" ]; then
        brightnessctl -q --save
        touch "$TMP_FILE"
        brightnessctl -q set 0 
    else
        brightnessctl -q --restore
        rm "$TMP_FILE"
    fi
}

set_clipped() {
    brightnessctl set -q --min-value=1 "$1"
}

increase() {
    set_clipped +"$DEFAULT_CHANGE"
}

decrease() {
    set_clipped "$DEFAULT_CHANGE"-
}

get_percentage() {
    local max_brightness="$1"
    local current="$(brightnessctl get)"
    echo $(("$current" * 100 / "$max_brightness"))
}

listen() {
    local max_brightness="$(brightnessctl max)"

    get_percentage "$max_brightness"

    udevadm monitor --property --subsystem-match=backlight \
        | grep --line-buffered ACTION=change \
        | while read;
    do
        get_percentage "$max_brightness"
    done
}

main "$@"
