#!/usr/bin/bash
KITTY_DIR=~/.config/kitty

get_background_opacity() {
    if [ -f "$1" ]; then
        local opacity=$(grep '^background_opacity' "$1" \
            | tail -1 \
            | awk '{ print $2 }' 2> /dev/null)
    else
        return 1
    fi

    if [ -n "$opacity" ]; then
        echo "$opacity"
    else
        return 1
    fi
}

export BACKGROUND_OPACITY=$(get_background_opacity "$KITTY_DIR/local.conf" \
                         || get_background_opacity "$KITTY_DIR/kitty.conf" \
                         || echo 1)

kitty --listen-on unix:$(mktemp -u /run/user/$UID/kitty.XXXX.sock) "$@"
