#!/usr/bin/bash

GAPS=12

function main {
    case "$1" in
        toggle_gaps)
            toggle_gaps;
            return 0;;
        *)
            return 1;;
    esac
}

function set {
    gsettings set org.gnome.shell.extensions.pop-shell "$1" "$2"
}

function get {
    gsettings get org.gnome.shell.extensions.pop-shell "$1"
}

function toggle_gaps {
    if [ $(get 'gap-outer' | awk '{print $2}') = 0 ]; then
        set gap-outer $GAPS; set gap-inner $GAPS
    else
        set gap-outer 0; set gap-inner 0
    fi
}

main $@
