#!/usr/bin/bash

set -e
set -u

if [ -n "${SUDO_ASKPASS-}" ]; then
    SUDO_CMD="sudo -A"
else
    SUDO_CMD="sudo"
fi

$SUDO_CMD echo -n
sleep 1

if [ -d ~/.themes/FlatWaita-16 ]; then
    if [ -d /usr/share/themes/FlatWaita-16 ]; then
        $SUDO_CMD rm -r /usr/share/themes/FlatWaita-16
    fi
    $SUDO_CMD bash -c "cd \"$HOME/.themes/FlatWaita-16\" && make system-install"
fi

for wallpaper in current current_blurred; do
    if [ -f ~/Wallpaper/"$wallpaper" ]; then
        $SUDO_CMD cp -H ~/Wallpaper/"$wallpaper" /usr/share/backgrounds/
    fi
done
