#!/usr/bin/bash

DOC_DIR="${XDG_DOCUMENTS_DIR:-$HOME/Documents}"
PROMPT="Open Document"
ROFI_OPTIONS=(-fixed-num-lines)

list_options()
{
    find -L "${DOC_DIR}/" -type f -regex '.*\.\(pdf\|epub\|djvu\)' | awk -v del="${DOC_DIR}/" '{sub(del, ""); print}'
}

callback()
{
    xdg-open "${DOC_DIR}/$1"
}

source ~/.local/libexec/prompt.sh
