#!/usr/bin/bash

PROMPT="$(echo "${1-Password}" | sed 's/: \?$//')"

ROFI_OPTIONS=(
    -password
    -theme-str 'window {width: 25%;} inputbar {children: [prompt,textbox-prompt-colon,entry];} entry {placeholder: "Enter password";}'
    -no-fixed-num-lines
)


list_options() {
    true
}


callback() {
    echo "$@"
}


source ~/.config/rofi/scripts/prompt.sh
