#!/usr/bin/bash

FF_DIR="$HOME/.firefox"

PROMPT="Choose Firefox Profile"
ROFI_OPTIONS=(-no-fixed-num-lines)

list_options()
{
    ls "$FF_DIR/profiles"
}

callback()
{
    # Weird workaround for playing DRM content
    # ln -sf "$FF_DIR/profiles/$1" "/tmp/ff-profile-$1"
    # firefox --profile "/tmp/ff-profile-$1"
    firefox --profile "$FF_DIR/profiles/$1"
}

source ~/.local/libexec/prompt.sh
