#!/usr/bin/bash

LAYOUTS_DIR="$HOME/.config/sway/input"

PROMPT="Choose keyboard layout"

if [ "${1-}" = "--sway" ]; then
    CALLBACK=(swaymsg input '*' xkb_file)
else
    CALLBACK=#TODO
fi

list_options()
{
    ls "$LAYOUTS_DIR"
}

callback()
{
    "${CALLBACK[@]}" "$LAYOUTS_DIR/$1"
}

source ~/.local/share/scripts/rofi-prompt.sh
