#!/usr/bin/bash

DOC_DIR="${XDG_DOCUMENTS_DIR:-$HOME/Documents}"
PROMPT="Open Document"

if [ "$(basename "$0")" = wofi-open ]; then
    CMD=(
        wofi
        --dmenu
        --insensitive
        --prompt "$PROMPT"
        --matching contains
    )
else
    CMD=(
        rofi
        -dmenu -i
        -p "$PROMPT"
        -no-show-icons
        -sorting-method levenshtein
        -matching normal
    )
fi

OUTPUT=$(find "${DOC_DIR}/" -type f | awk -v "del"="${DOC_DIR}/" '{sub(del, ""); print}' | "${CMD[@]}")

[ -n "${OUTPUT-}" ] && xdg-open "${DOC_DIR}/${OUTPUT}"
