#!/usr/bin/bash

PROMPT="Choose keyboard layout"

list_options()
{
    if [ "$XDG_CURRENT_DESKTOP" = "sway" ]; then
        ls "$HOME/.config/sway/input"
    elif [ "$XDG_CURRENT_DESKTOP" = "i3" ]; then
        ls "$HOME/.config/i3/xkbmap"
    fi
}

callback()
{
    if [ "$XDG_CURRENT_DESKTOP" = "sway" ]; then
        swaymsg input '*' xkb_file "$1"
    elif [ "$XDG_CURRENT_DESKTOP" = "i3" ]; then
        setxkbmap $(cat "$HOME/.config/i3/xkbmap/$1")
    fi
}

source ~/.config/rofi/scripts/prompt.sh
