#!/usr/bin/bash

#ROFI_FLAGS+=(-matching normal)

#rofi -show emoji -modi emoji "${ROFI_FLAGS[@]}"

#ROFI_FLAGS=('-i' '-p' 'Open Document' '-no-show-icons')


#xdg-open "${DOC_DIR}/${OUTPUT:?}"

FF_DIR="$HOME/.mozilla/firefox"

ROFI_FLAGS=()
ROFI_FLAGS+=(-no-sorting -no-show-icons)
ROFI_FLAGS+=(-i -p 'Choose Firefox Profile')

OUTPUT=$(awk '/Name=/{sub("Name=",""); print}' "$FF_DIR/profiles.ini" | rofi -dmenu "${ROFI_FLAGS[@]}")
firefox -p "${OUTPUT:?}"
