#!/usr/bin/bash

PROMPT="$(echo "${1-Password}" | sed 's/: \?$//')"
THEME_STRING='window {width: 25%;} inputbar {children: [prompt,textbox-prompt-colon,entry];} entry {placeholder: "Enter password";}'

if [ "$(basename "$0")" = wofi-askpass ]; then
    CMD=(
        wofi
        --dmenu
        --password
        --insensitive
        --prompt "$PROMPT"
    )
else
    CMD=(
        rofi
        -dmenu
        -password
        -p "$PROMPT"
        -theme-str "$THEME_STRING" \
        -no-fixed-num-lines
    )
fi

"${CMD[@]}"
