#!/usr/bin/bash

CONFIG_DIR="/etc/openvpn/ivpn/"

PROMPT="Choose Server"

vpn_is_running()
{
    pgrep --exact openvpn &>/dev/null
}

list_options()
{
    if vpn_is_running; then
        echo "Stop"
    fi

    find "$CONFIG_DIR" -type f -name '*.ovpn' 2>/dev/null \
        | sed "s#^${CONFIG_DIR}##"
}

callback()
{
    if vpn_is_running; then
        pkexec killall --exact openvpn
    fi

    if [ "$1" != Stop ]; then
        pkexec openvpn "$CONFIG_DIR/$1" > /tmp/openvpn.log
    fi
}

source ~/.local/libexec/prompt.sh
