#!/usr/bin/bash

FF_DIR="$HOME/.mozilla/firefox"
PROMPT="Choose Firefox Profile"

PROFILES="$(awk '/Name=/{sub("Name=",""); print}' "$FF_DIR/profiles.ini")"

if [ "$(basename "$0")" = wofi-ff ]; then
    CMD=(
        wofi
        --dmenu
        --insensitive
        --prompt "$PROMPT"
        --matching contains
        --lines "$(echo "$PROFILES" | wc -l)"
    )
else
    CMD=(
        rofi
        -dmenu -i
        -p "$PROMPT"
        -no-show-icons
        -sorting-method levenshtein
        -matching normal
        -lines "$(echo "$PROFILES" | wc -l)"
    )
fi

SELECTION="$(echo "$PROFILES" | "${CMD[@]}")"
[ -n "${SELECTION-}" ] && firefox -p "${SELECTION:?}"
