#!/usr/bin/bash
WALLPAPER_DIR="$HOME/Wallpaper"

wallpaper="${1:-$(cat /tmp/current_scheme 2>/dev/null)}"
[ -z "$wallpaper" ] && exit

for suffix in "" _blurred _wide _wide_blurred; do
    file=$(ls "$WALLPAPER_DIR" | grep "^${wallpaper}${suffix}\." \
                               | head -1)
    if [ -n "$file" ]; then
        ln -fs "$WALLPAPER_DIR/$file" "$WALLPAPER_DIR/current$suffix"
    fi
done

if [ -n "$1" ]; then
    case "$DESKTOP_SESSION" in
        sway)
            swaymsg -- output '*' bg ~/Wallpaper/current fill
            ;;
    esac
fi
