#!/usr/bin/bash

WALLPAPER_DIR="$HOME/Wallpaper"

wallpaper=$(cat /tmp/current_wallpaper 2>/dev/null)

file_normal=$(ls "$WALLPAPER_DIR" | grep "^${wallpaper}\.")
file_blurred=$(ls "$WALLPAPER_DIR" | grep "^${wallpaper}_blurred\.")

if [ -n "$file_normal" ]; then
    ln -fs "$WALLPAPER_DIR/$file_normal" "$WALLPAPER_DIR/current"
fi

if [ -n "$file_blurred" ]; then
    ln -fs "$WALLPAPER_DIR/$file_blurred" "$WALLPAPER_DIR/current_blurred"
fi

case "$DESKTOP_SESSION" in
    sway)
        #swaymsg -- output '*' bg ~/Wallpaper/current fill
        ;;
esac
