#!/usr/bin/bash

LOCK=/tmp/idle.lock
DEFAULT_TIMOUT=180

if [ -f "$LOCK" ]; then
    old="$(cat $LOCK)"
    if [ -z "$old" ]; then
        old="$DEFAULT_TIMOUT"
    fi
    xset s "$old"
    rm "$LOCK"
else
    old="$(xset q | grep timeout | awk '{ print $2 }')"
    if [ -z "$old" ] || [ "$old" -eq 0 ]; then
        old="$DEFAULT_TIMOUT"
    fi
    echo "$old" > "$LOCK"
    xset s off
fi
