#!/usr/bin/bash
swayidle timeout 5 'swaymsg "output * dpms off"' \
         resume    'swaymsg "output * dpms on"'  &
swaylock --no-unlock-indicator \
         --ignore-empty-password \
         "$@"
kill %% # kills the swayidle process
