#!/usr/bin/bash

pre_lock() {
    xset +dpms dpms 5 5 5
    xset dpms force off
}

post_lock() {
    xset dpms 0 0 0
}

#trap post_lock SIGHUP SIGINT SIGTERM EXIT
#pre_lock

RED='#cf3b1a'
GREEN='#73C48F'
#YELLOW='#FFCE51'
#BLUE='#48B9C7'
#MAGENTA='#AD7FA8'
#CYAN='#34E2E2'
BLACK='#333333'
GREY='#4d4d4d'

CLEAR='#00000000'
BG=$GREY'cc'
RING=$BLACK
TEXT=$GREEN
HL=$GREEN'bb'
WRONG=$RED'bb'
WALLPAPER="/usr/share/backgrounds/mywallpaper-blurred.png"

i3lock \
--pass-media-keys \
--pass-screen-keys \
--pass-volume-keys \
--screen 1 \
--time-color=$TEXT \
--date-color=$TEXT \
--clock \
--indicator \
--time-str="%H:%M:%S" \
--date-str="%A, %m %Y" \
\
--inside-color=$BG \
--ring-color=$RING \
--line-color=$CLEAR \
--separator-color=$CLEAR \
\
--verif-text="" \
--verif-color=$TEXT \
--insidever-color=$BG \
--ringver-color=$HL \
\
--wrong-text="" \
--wrong-color=$WRONG \
--insidewrong-color=$BG \
--ringwrong-color=$WRONG \
\
--keyhl-color=$HL \
--bshl-color=$HL \
\
--noinput-text="" \
$@ \
-i "$WALLPAPER"
#-B 5
