#!/usr/bin/bash

I3_CONF=~/.config/i3/config

HEADER="\
WARNING: Do not change this file directly. Instead make your changes to
~/.config/i3/config.in and run ~/.local/share/scripts/generate-i3-config.sh afterwards.
"

if [ -f ~/.config/i3/config ] && ! grep -q '^WARNING: Do not change this file directly' "$I3_CONF"; then
    echo "The file ${I3_CONF} already exists and was not generated by this script."
    echo "Please remove it and then run this script again."
    exit 1
fi

{
    echo "$HEADER"
    cat /etc/colors/i3.conf \
        || cat ~/.config/i3/flavours \
        || cat ~/.config/sway/flavours
    cat ~/.config/i3/config.in
} 2>/dev/null > "$I3_CONF"
