if [ -n "${TOOLBOX_PATH}" ] && [ -x /usr/bin/fish ]; then
    source /etc/profile
    exec /usr/bin/fish
fi

if [ -x "/usr/bin/ssh-agent" ]; then
    eval `ssh-agent` > /dev/null
fi

# vim: filetype=sh
